header:
  version: 15
  includes:
    - includes/base.yml
    - machine/v2h.yml
    - includes/imdt.yml
  # features
    - features/v2h-drpai.yml
  # proprietary feature layers
    # - features/graphics.yml
    # - features/codecs.yml
  # image
    - images/weston.yml

local_conf_header:
  buildinfo: |
    INHERIT += "image-buildinfo"